name: weather_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  dio: ^4.0.0
  equatable: ^2.0.3
  http: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cloud.png
